import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// 这段代码运行在 Node.js 环境 - 不要在这里使用客户端代码（浏览器 API、JSX 等）

/**
 * 创建侧边栏使你能够：
 - 创建一个有序的文档组
 - 为该组的每个文档渲染一个侧边栏
 - 提供上一个/下一个导航

 侧边栏可以从文件系统生成，也可以在此处显式定义。

 创建任意数量的侧边栏。
 */
const sidebars: SidebarsConfig = {
  // 默认情况下，Docusaurus 从 docs 文件夹结构生成侧边栏
  userSidebar: [
    {type: 'autogenerated', dirName: 'UserDocs'}
  ],
  adminSidebar: [
    {type: 'autogenerated', dirName: 'AdminDocs'}
  ],
  aboutSidebar: [
    {type: 'autogenerated', dirName: 'About'}
  ]

  // 但是你可以手动创建侧边栏
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
